#!/bin/bash
# Builds build/Kay.app from the SwiftPM executable.
#
# This is the input to the release pipeline (`asc notarize kay`, which re-signs it with
# Developer ID, hardened runtime and macOS/Resources/Kay.entitlements). Do not run the result
# day to day: install the released image with `make install`, the same file users get.
set -euo pipefail

# The package (macOS app + Shared/) builds from the repository root; output goes to <root>/build.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RES="$ROOT/macOS/Resources"
APP="$ROOT/build/Kay.app"
# Identity and version live only in macOS/Resources/Info.plist; the pipeline reads it too.
PLIST="$RES/Info.plist"
VERSION="$(/usr/bin/plutil -extract CFBundleShortVersionString raw "$PLIST")"

cd "$ROOT"
echo "==> swift build -c release"
swift build -c release
BIN="$(swift build -c release --show-bin-path)/Kay"

echo "==> assembling $APP ($VERSION)"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$BIN" "$APP/Contents/MacOS/Kay"
cp "$PLIST" "$APP/Contents/Info.plist"
cp "$RES/AppIcon.icns" "$APP/Contents/Resources/AppIcon.icns"
# Strings are looked up in Bundle.main, so the .lproj folders sit in Contents/Resources
# (SwiftPM resources would land in a separate bundle). Generated by scripts/localize.py.
for LPROJ in "$RES"/*.lproj; do
	ditto "$LPROJ" "$APP/Contents/Resources/$(basename "$LPROJ")"
done

IDENTITY="${SIGN_IDENTITY:-$(security find-identity -v -p codesigning 2>/dev/null \
	| grep -oE '"Developer ID Application[^"]*"' | head -1 | tr -d '"' || true)}"
if [ -n "$IDENTITY" ]; then
	echo "==> signing with: $IDENTITY"
	codesign --force --options runtime --timestamp \
		--entitlements "$RES/Kay.entitlements" --sign "$IDENTITY" "$APP"
	codesign --verify --deep --strict "$APP"
else
	echo "==> no Developer ID identity found, using ad-hoc"
	codesign --force --sign - "$APP"
fi

echo "==> done: $APP"
